const { debug, info } = require('@actions/core');
const { readFileSync, writeFileSync, existsSync } = require('fs');
const { join } = require('path');
const download = require('image-downloader');
const { rmRF, cp } = require('@actions/io');
const type_list = ['views', 'clones', 'paths', 'referrers'];
const repository = process.env['GITHUB_REPOSITORY'].split(`/`);
const author = repository[0];
const work = repository[1];

let LICENSEGenerator = async function (branch, year) {
  debug(`work: ${work}`);
  debug(`author: ${author}`);
  debug(`branch: ${branch}`);
  var template = join(__dirname, '../template/CC-BY-NC-ND-4.0.template');
  var LICENSE = join(branch, 'LICENSE');
  try {
    if (existsSync(LICENSE)) await rmRF(LICENSE);
    await cp(template, LICENSE, { recursive: true, force: false });
    info('[INFO]: Copy completed, and the LICENSE template from:');
    info('[INFO]: ' + template);
    var data = readFileSync(LICENSE, 'utf-8');
    info('[INFO]: Read completed, and the LICENSE from');
    info('[INFO]: ' + LICENSE);
    var _year = new Date().getFullYear();
    info(`[INFO]: Now year: ${_year}`);
    if (year === '') year = _year;
    if (parseInt(year) != _year) _year = `${year}-${_year}`;
    info(`[INFO]: LICENSE year: ${_year}`);
    data = data
      .replace(/{author}/g, author)
      .replace(/{year}/g, _year)
      .replace(/{work}/g, work);
    writeFileSync(LICENSE, data, 'utf-8');
    info('[INFO]: Successfully generate LICENSE');
    info('[INFO]: LICENSE in ' + LICENSE);
    debug('Write completed and the data is:');
    debug(data);
  } catch (error) {
    debug('[LICENSEGenerator]: ' + error);
    throw Error(error.message);
  }
};

let READMEGenerator = async function (branch_path, repos) {
  const branch = branch_path.substr(1);
  const README_template = join(__dirname, '../template/README.template');
  const README = join(branch_path, 'README.md');
  try {
    if (existsSync(README)) await rmRF(README);
    info('[INFO]: Clear completed, and the README from');
    info('[INFO]: ' + README);
    const _data = readFileSync(README_template, 'utf-8');
    info('[INFO]: Read completed, and the README template from:');
    info('[INFO]: ' + README_template);
    var data =
      '# ⚡️ Traffic badge\n\n' +
      '**All data is automatically generated by [Traffic to Badge - GitHub Action]' +
      '(https://github.com/marketplace/actions/traffic-to-badge).**\n\n' +
      '**Example usage repository: [yi-Xu-0100/traffic2badge](https://github.com/yi-Xu-0100/traffic2badge).**\n\n' +
      _data
        .replace(/{author}/g, author)
        .replace(/{work}/g, work)
        .replace(/{branch}/g, branch)
        .replace(/{repo}/g, 'total-traffic-data-badge')
        .replace(/{link}/g, branch + '#readme');
    for (let i = 0; i < repos.length; i++) {
      data =
        data +
        '\n' +
        _data
          .replace(/{author}/g, author)
          .replace(/{work}/g, work)
          .replace(/{branch}/g, branch)
          .replace(/{repo}/g, repos[i])
          .replace(/{link}/g, branch + `/traffic-${repos[i]}`)
          .replace(/total /g, '')
          .replace(/total_/g, '');
    }
    writeFileSync(README, data, 'utf-8');
    info('[INFO]: Successfully generate README');
    info('[INFO]: README in ' + README);
    debug('Write completed and the data is:');
    debug(data);
  } catch (error) {
    debug('[READMEGenerator]: ' + error);
    throw Error(error.message);
  }
};

let SVGGenerator = async function (
  data,
  path,
  views_color,
  clones_color,
  logo,
  week = false,
  total = false
) {
  const color = [views_color, clones_color];
  const type_default = [58, 62]; //left-label-width
  for (let i = 0; i < 2; i++) {
    let _SVGType = `${(total && 'total ') || ''}${type_list[i]}${(week && ' per week') || ''}`;
    if (color[i] === 'brightgreen' && logo === 'github') {
      info(`[INFO]:Start generate ${_SVGType} SVG`);
      debug(`type: ${type_list[i]}`);
      let type_left = type_default[i];
      debug(`type_left: ${type_left}`);
      let left_x = type_left * 5 + 95;
      debug(`left_x: ${left_x}`);
      let text_length = type_left * 10 - 270;
      debug(`text_length: ${text_length}`);
      let number = parseInt(data[type_list[i]].count, 10);
      debug(`data[${_SVGType}].count: ` + data[type_list[i]].count);
      debug(`number: ${number}`);
      let number_magnitude = number.toString().length;
      debug(`number_magnitude: ${number_magnitude}`);
      let right_width =
        (number_magnitude % 2 ? 31 : 23) + (parseInt(number_magnitude / 2, 10) - 1) * 14;
      debug(`right_width: ${right_width}`);
      let SVG_width = type_left + right_width;
      debug(`SVG_width: ${SVG_width}`);
      let right_x = right_width * 5 + type_left * 10 - 10;
      debug(`right_x: ${right_x}`);
      let number_length = right_width * 10 - 100;
      debug(`number_length: ${number_length}`);
      let template = join(__dirname, '../template/SVG.template');
      let SVG = join(path, `${_SVGType.replace(/ /g, '_')}.svg`);
      let _data = readFileSync(template, 'utf-8');
      writeFileSync(
        SVG,
        _data
          .replace(/{type}/g, `${(total && 'total ') || ''}${type_list[i]}`)
          .replace(/{number}/g, `${number}${(week && '/week') || ''}`)
          .replace(/{SVG_width}/g, `${SVG_width + ((week && 34) || 0) + ((total && 28) || 0)}`)
          .replace(/{type_left}/g, `${type_left + ((total && 28) || 0)}`)
          .replace(/{right_width}/g, `${right_width + ((week && 34) || 0)}`)
          .replace(/{left_x}/g, `${left_x + ((total && 140) || 0)}`)
          .replace(/{text_length}/g, `${text_length + ((total && 280) || 0)}`)
          .replace(/{right_x}/g, `${right_x + ((week && 170) || 0) + ((total && 280) || 0)}`)
          .replace(/{number_length}/g, `${number_length + ((week && 340) || 0)}`),
        'utf-8'
      );
      info(`[INFO]: Successfully generate ${_SVGType} SVG`);
      info(`[INFO]: ${_SVGType.replace(/ /g, '_')}.svg path: ${SVG}`);
    } else if (process.env['local_debug'] === 'true') {
      info(`[INFO]: Skip download ${_SVGType} SVG`);
    } else {
      info(`[INFO]:Start download ${_SVGType} SVG`);
      let options = {
        url:
          `https://img.shields.io/badge/${(total && 'total_') || ''}${type_list[i]}-` +
          data[type_list[i]].count +
          ((week && '/week') || '') +
          `-${color[i].replace('#', '')}?logo=${logo}`,
        dest: `${path}/${_SVGType.replace(/ /g, '_')}.svg`
      };
      await download
        .image(options)
        .then(({ filename }) => {
          info(`[INFO]: Successfully download ${_SVGType} SVG`);
          info(`[INFO]: ${_SVGType.replace(/ /g, '_')}.svg path:`);
          info('[INFO]: ' + filename);
        })
        .catch(error => {
          debug('[SVGGenerator]: ' + error);
          throw Error(error.message);
        });
    }
  }
};

let dataGenerator = async function (data, path, week) {
  for (let i = 0; i < type_list.length; i++) {
    debug(`Start generate traffic_${type_list[i]}${(week && '_per_week') || ''}.json`);
    let file_path = join(path, `traffic_${type_list[i]}${(week && '_per_week') || ''}.json`);
    let file_data = data[type_list[i]];
    try {
      writeFileSync(file_path, JSON.stringify(file_data, null, 2), 'utf-8');
      info(`[INFO]: ${type_list[i]}${(week && '_per_week') || ''} Traffic data path:`);
      info('[INFO]: ' + file_path);
    } catch (error) {
      debug(`${type_list[i]}${(week && '_per_week') || ''} file_data:`);
      debug(file_data);
      debug('[dataGenerator]: ' + error);
      throw Error(error.message);
    }
    debug(`Successfully generate traffic_${type_list[i]}${(week && '_per_week') || ''}.json`);
    if (week && i === 1) break;
  }
};

module.exports = {
  LICENSEGenerator,
  READMEGenerator,
  SVGGenerator,
  dataGenerator
};
