name: sync2gitee(cached)
# version: 1.2.1
# author: [yiXu](https://github.com/yi-Xu-0100)
# guide: [yi-Xu-0100/hub-mirror](https://github.com/yi-Xu-0100/hub-mirror)
# template: [sync2gitee.cached.yml](https://github.com/yi-Xu-0100/hub-mirror/blob/main/template/sync2gitee.cached.yml)
# lastmod: 2020-10-11 13:59:24

on:
  push:
  schedule:
    # UTC 17:00 -> CST (China) 1:00 see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 17 * * *'

jobs:
  run:
    name: Sync GitHub to Gitee(Cached)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.3

      - name: Get repo and time
        id: info
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
            return context.repo.repo;
      - name: Cache src repos
        uses: actions/cache@v2.1.2
        id: cache
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: ${{ runner.os }}-${{ github.repository_owner }}-${{ steps.info.outputs.result }}-cache-${{ steps.info.outputs.time }}
          restore-keys: ${{ runner.os }}-${{ github.repository_owner }}-${{ steps.info.outputs.result }}-cache-

      - name: Mirror the GitHub repos to Gitee with cache
        uses: Yikun/hub-mirror-action@v0.10
        with:
          src: github/yi-Xu-0100
          dst: gitee/yiXu0100
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: '${{ steps.info.outputs.result }}'
          cache_path: /github/workspace/hub-mirror-cache
          account_type: user
          force_update: true

      - name: Print cache path
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache
